name: Build & Release Magisk Module

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up variables
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          VERSION_CODE=$(echo $VERSION | awk -F. '{ printf("%d%02d%02d", $1,$2,$3) }')
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV

      - name: Zip Magisk module
        run: |
          cd mihomo-magisk
          zip -r ../mihomo-magisk.zip ./*
          cd ..

      - name: Clean and fetch tags
        run: |
          git tag -l | xargs -r git tag -d
          git fetch origin 'refs/tags/*:refs/tags/*' --force

      - name: Generate CHANGELOG.md
        run: |
          PREV_TAG=$(git tag --sort=-creatordate | sed -n 2p)
          if [ -z "$PREV_TAG" ]; then
            git log --pretty=format:"* %s" > CHANGELOG.md
          else
            git log $PREV_TAG..HEAD --pretty=format:"* %s" > CHANGELOG.md
          fi


      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.TAG_NAME }}
          files: |
            mihomo-magisk.zip
            CHANGELOG.md
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 